-- 0021_v0170_legal_cards.sql — AUDITORIA LEGAL E FISCAL POR RECEITA (FASE 6)
--
-- Nove cartas, uma por regra de receita, com a base normativa CONSULTADA EM FONTE OFICIAL, a fonte
-- nomeada e a data da verificação.
--
-- O QUE ESTAS CARTAS SÃO E O QUE NÃO SÃO
--
-- São pesquisa. `certainty` é o grau de certeza DA PESQUISA, não de um parecer. `needs_lawyer` é
-- **verdadeiro em todas as nove**, e `needs_accountant` em todas as que têm questão tributária aberta.
-- Os documentos desta rodada são explícitos: "Não invente legislação. Não trate opinião do modelo como
-- parecer jurídico" e "NUNCA afirmar que uma estrutura é legal apenas porque não foi encontrada uma
-- proibição".
--
-- RESULTADO: **nenhuma carta é verde.** Cinco amarelas, quatro vermelhas. Como
-- `monetization_rule_gate()` recusa ativar regra sem carta verde, o estado do produto depois desta
-- migração é: **nada cobrável** — com o motivo de cada bloqueio escrito e a base citada.
--
-- As quatro vermelhas viram `legal_status = 'refused'`, que é mais forte que `review_required`: não é
-- "ainda não analisado", é "analisado e não implementar assim".
--
-- FONTES CONSULTADAS (texto literal, em 2026-10-06):
--   * Lei Complementar 116/2003, lista anexa, itens 1.03, 1.04, 1.05 e 1.07 — planalto.gov.br
--   * STF, ADI 1945 e ADI 5659, julgadas em 18/02/2021 (ISS e não ICMS sobre licenciamento de
--     software), com modulação de efeitos aprovada em 24/02/2021
--   * Lei 12.865/2013, arts. 6º e 9º (arranjo de pagamento, instituição de pagamento, autorização do
--     Banco Central) — planalto.gov.br
--   * Lei 14.133/2021, art. 2º, VII (contratações de tecnologia da informação pela administração
--     pública) — planalto.gov.br
--   * Lei 13.709/2018 (LGPD), arts. 5º, III e XI, e 12 (dado anonimizado) — planalto.gov.br


-- saas.institutional.funder — carta YELLOW
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('saas.institutional.funder', 'yellow', 'medium', 'Fundação, instituto, empresa ou fundo que administra programa de financiamento', 'A plataforma (pessoa jurídica titular do software)', 'Assinatura vigente do serviço, por período contratado', 'Receita de prestação de serviço de software (licenciamento de uso e hospedagem)', 'Contrato de prestação de serviço ou adesão a Termos de Uso, com aceite versionado e registro de IP e data', 'Contrato ou Termos de Uso aceitos; nota fiscal de serviço', 'Termos de Uso, Termos de Assinatura, Política de Privacidade, Política de Cancelamento e de Reembolso', 'Cancelamento por autosserviço (POST /v1/billing/cancel), com acesso mantido até o fim do período já pago', 'A definir com o jurídico; o Código de Defesa do Consumidor pode não se aplicar em contrato entre pessoas jurídicas, e isso precisa ser confirmado', 'Enquadramento provável em ISS (municipal) pelos itens 1.03/1.05/1.07 da LC 116/2003, conforme ADI 1945 e 5659. A alíquota, o município competente e o regime tributário da empresa NÃO foram analisados.', 'Emissão de nota fiscal de serviço é obrigatória e NÃO está implementada na plataforma', 'Não há atividade regulada identificada nesta modalidade: é venda de software, sem custódia de recurso de terceiro.', 'Lei Complementar 116/2003, lista anexa: item 1.03 ''Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres''; item 1.05 ''Licenciamento ou cessão de direito de uso de programas de computação''; item 1.07 ''Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados''. STF, ADI 1945 e ADI 5659, julgadas em 18/02/2021: incide ISS, e não ICMS, sobre o licenciamento de software, com modulação de efeitos aprovada em 24/02/2021.', 'Planalto — Lei Complementar 116/2003 (texto literal dos itens) + STF ADI 1945 e 5659', 'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm', '2026-10-06', 'Alíquota e município de incidência do ISS. Regime tributário da pessoa jurídica. Aplicabilidade do CDC em contrato entre pessoas jurídicas. Redação final dos Termos. Emissão de nota fiscal.', 'Esta é a modalidade com MENOR risco identificado: é prestação de serviço de software, sem intermediação financeira e sem recurso público passando pela plataforma. Ainda assim fica AMARELA, porque definir alíquota, município e nota fiscal é trabalho de contador.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- b2g.territorial_governance — carta RED
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('b2g.territorial_governance', 'red', 'medium', 'Prefeitura, estado, secretaria, autarquia ou fundo público', 'A plataforma', 'Contrato administrativo vigente', 'Receita de prestação de serviço de tecnologia da informação a órgão público', 'Contrato administrativo, precedido de licitação ou de contratação direta regularmente enquadrada', 'Instrumento contratual administrativo; nota fiscal; comprovação de regularidade fiscal e trabalhista', 'Termos específicos para administração pública, distintos dos Termos de adesão comuns', 'Regida pelo contrato administrativo e pela Lei 14.133/2021, não por autosserviço', 'Regida pelo contrato administrativo', 'ISS sobre o serviço, mais retenções que o órgão contratante pode ser obrigado a fazer. Nada disso foi analisado.', 'Nota fiscal e, em regra, comprovação de regularidade a cada pagamento', 'A contratação por órgão público NÃO pode ser feita por checkout de autosserviço. Oferecer contratação online a um órgão sem procedimento prévio é o risco central desta modalidade.', 'Lei 14.133/2021, art. 2º, VII: a Lei aplica-se a ''contratações de tecnologia da informação e de comunicação''. A regra geral para a administração pública contratar software ou serviço é, portanto, a licitação, nas modalidades e critérios da própria Lei; contratação direta depende de enquadramento em hipótese de dispensa (art. 75) ou inexigibilidade (art. 74), que não foi analisado aqui.', 'Planalto — Lei 14.133/2021, art. 2º, VII (texto literal)', 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm', '2026-10-06', 'Enquadramento em dispensa (art. 75) ou inexigibilidade (art. 74) — NÃO analisado. Cadastro no órgão. Exigências de regularidade. Retenções tributárias. Necessidade de pregão e de termo de referência.', 'VERMELHA de propósito: tecnicamente a plataforma consegue faturar; juridicamente a contratação pública tem regime próprio e exige licitação como regra. A implementação NÃO deve oferecer checkout para órgão público.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- enterprise.esg_portfolio — carta YELLOW
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('enterprise.esg_portfolio', 'yellow', 'medium', 'Empresa que mantém programa de investimento social ou precisa comprovar impacto', 'A plataforma', 'Contrato vigente, por período', 'Receita de prestação de serviço de software', 'Contrato de prestação de serviço entre pessoas jurídicas', 'Contrato; nota fiscal de serviço', 'Termos de Uso empresariais, acordo de tratamento de dados quando a empresa for controladora de dados pessoais', 'Conforme contrato; sem autosserviço quando houver prazo mínimo', 'A definir com o jurídico', 'Mesmo enquadramento provável em ISS da modalidade institucional. Não analisado em detalhe.', 'Nota fiscal obrigatória, não implementada', 'Se a plataforma gerar relatório que a empresa use em divulgação de ESG, há risco REPUTACIONAL e possivelmente regulatório de a afirmação não se sustentar. A mitigação implementada é estrutural: a cadeia de resultado devolve a FORÇA declarada de cada elo e não promove hipótese a evidência.', 'Lei Complementar 116/2003, lista anexa: item 1.03 ''Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres''; item 1.05 ''Licenciamento ou cessão de direito de uso de programas de computação''; item 1.07 ''Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados''. STF, ADI 1945 e ADI 5659, julgadas em 18/02/2021: incide ISS, e não ICMS, sobre o licenciamento de software, com modulação de efeitos aprovada em 24/02/2021.', 'Planalto — Lei Complementar 116/2003 (texto literal dos itens) + STF ADI 1945 e 5659', 'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm', '2026-10-06', 'Responsabilidade da plataforma sobre afirmação de impacto publicada pela empresa. Acordo de tratamento de dados. Regras de divulgação de ESG aplicáveis ao cliente.', 'Mesmo risco tributário da institucional, mais uma pergunta aberta sobre responsabilidade por afirmação de impacto.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- implementation.setup — carta YELLOW
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('implementation.setup', 'yellow', 'medium', 'Organização contratante', 'A plataforma', 'Entrega da implantação, integração ou migração contratada', 'Receita de prestação de serviço técnico', 'Contrato de serviço com escopo e entrega definidos', 'Contrato com escopo; aceite de entrega; nota fiscal', 'Termos de serviço profissional, distintos dos Termos de assinatura', 'Conforme contrato, com regra de pagamento proporcional ao executado', 'A definir com o jurídico', 'Pode cair em item diverso da LC 116/2003 conforme o escopo (suporte técnico, item 1.07, ou elaboração de programa, item 1.04). O enquadramento depende do que for efetivamente feito.', 'Nota fiscal obrigatória, não implementada', 'Serviço humano: pode gerar discussão trabalhista se executado por pessoa física sem vínculo adequado.', 'Lei Complementar 116/2003, lista anexa: item 1.03 ''Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres''; item 1.05 ''Licenciamento ou cessão de direito de uso de programas de computação''; item 1.07 ''Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados''. STF, ADI 1945 e ADI 5659, julgadas em 18/02/2021: incide ISS, e não ICMS, sobre o licenciamento de software, com modulação de efeitos aprovada em 24/02/2021.', 'Planalto — Lei Complementar 116/2003 (texto literal dos itens) + STF ADI 1945 e 5659', 'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm', '2026-10-06', 'Enquadramento do item da lista de serviços conforme escopo. Forma de contratação de quem executa.', 'O enquadramento tributário varia com o escopo, então não há resposta única.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- marketplace.take_rate — carta RED
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('marketplace.take_rate', 'red', 'high', 'Organização contratante ou prestador de serviço', 'A plataforma', 'Contratação concluída entre duas partes dentro da plataforma', 'Comissão por intermediação', 'Exigiria contrato de intermediação com as duas partes, que não existe', 'Contrato de intermediação; nota fiscal de comissão', 'Termos de Marketplace e de Intermediação, que não existem', 'Indefinida', 'Indefinida — e reembolso de comissão sobre serviço já prestado é problema por si', 'Comissão de intermediação tem enquadramento próprio na LC 116/2003 (itens de agenciamento e intermediação), não analisado. Se a plataforma receber e repassar dinheiro, surge discussão sobre a base de cálculo.', 'Nota fiscal de comissão, não implementada', 'Cobrar percentual sobre transação pressupõe que a transação ocorra na plataforma. Receber recurso de terceiro para repassar pode caracterizar atividade de instituição de pagamento, sujeita a autorização do Banco Central (Lei 12.865/2013, art. 9º, V). A ADR-022 e a ADR-031 estabelecem que a plataforma NÃO custodia nem processa aporte, justamente para evitar esse enquadramento.', 'Lei 12.865/2013, art. 6º: ''arranjo de pagamento'' é o conjunto de regras que disciplina a prestação de serviço de pagamento ao público aceito por mais de um recebedor; ''instituição de pagamento'' é a pessoa jurídica que, aderindo a um arranjo, tenha como atividade principal ou acessória, entre outras, executar instruções de pagamento, gerir conta de pagamento ou executar remessa de fundos. Art. 9º, V: compete ao Banco Central autorizar a constituição e o funcionamento de instituição de pagamento.', 'Planalto — Lei 12.865/2013, arts. 6º e 9º (texto literal)', 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12865.htm', '2026-10-06', 'Se a plataforma pode cobrar comissão SEM tocar no dinheiro (cobrando a comissão separadamente da parte, por fora da transação) — e se isso muda o enquadramento. Exige advogado especializado em meios de pagamento.', 'VERMELHA. Hoje o marketplace é vitrine: não há contratação com pagamento dentro da plataforma, logo não existe transação sobre a qual cobrar. O gatilho do banco recusa ativar esta regra citando a ADR-022.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- success_fee.funding — carta RED
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('success_fee.funding', 'red', 'high', 'Organização que recebeu o financiamento, ou quem financiou', 'A plataforma', 'Operação de financiamento concluída', 'Taxa de êxito — natureza a definir: comissão, corretagem ou prestação de serviço com remuneração variável', 'Exigiria contrato específico com a parte que paga, inexistente', 'Contrato de taxa de êxito; nota fiscal', 'Termos de Intermediação, inexistentes', 'Indefinida', 'Indefinida', 'Natureza da receita não definida, logo enquadramento tributário indefinido.', 'Não implementada', 'Risco mais alto de todos os motores. Cobrar percentual sobre recurso que transita pode caracterizar atividade de instituição de pagamento (Lei 12.865/2013, art. 6º e art. 9º, V, autorização do Banco Central). Se o recurso for PÚBLICO, somam-se as regras de parceria e de prestação de contas. Se houver captação junto a investidores, pode haver discussão sobre oferta de valores mobiliários e competência da CVM. Nada disso foi analisado, e nenhuma destas hipóteses pode ser descartada aqui.', 'Lei 12.865/2013, art. 6º: ''arranjo de pagamento'' é o conjunto de regras que disciplina a prestação de serviço de pagamento ao público aceito por mais de um recebedor; ''instituição de pagamento'' é a pessoa jurídica que, aderindo a um arranjo, tenha como atividade principal ou acessória, entre outras, executar instruções de pagamento, gerir conta de pagamento ou executar remessa de fundos. Art. 9º, V: compete ao Banco Central autorizar a constituição e o funcionamento de instituição de pagamento.', 'Planalto — Lei 12.865/2013, arts. 6º e 9º (texto literal)', 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12865.htm', '2026-10-06', 'Natureza jurídica da operação. Se há intermediação. Se há custódia. Se há recurso público. Se há oferta a investidores. Conflito de interesse quando quem recomenda a oportunidade é remunerado pelo êxito dela. TODAS exigem advogado.', 'VERMELHA, e a mais importante de todas. A ADR-022 existe precisamente para evitar este enquadramento, e desfazê-la é decisão jurídica — não técnica. A infraestrutura de cálculo fica desligada no banco, por gatilho.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- premium.readiness_analysis — carta YELLOW
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('premium.readiness_analysis', 'yellow', 'medium', 'Organização que propõe projeto (OSC ou equivalente)', 'A plataforma', 'Análise avançada de prontidão entregue', 'Receita de prestação de serviço de software, por operação', 'Contrato de adesão aos Termos de Uso, com aceite versionado', 'Termos aceitos; nota fiscal de serviço', 'Termos de Uso e Política de Reembolso específicos para compra por operação', 'Compra por operação: não há recorrência a cancelar', 'Ponto sensível: serviço digital entregue na hora. O direito de arrependimento do art. 49 do CDC aplica-se a compra fora do estabelecimento e precisa ser analisado para serviço de execução imediata.', 'ISS, pelos mesmos itens da LC 116/2003. Operação de valor baixo e volume alto exige atenção ao regime de emissão de nota.', 'Nota fiscal por operação, não implementada. Volume alto de notas de valor pequeno é problema operacional real.', 'Se a pagadora for OSC com recurso de projeto, pode haver regra do financiador sobre o que é despesa elegível — risco do CLIENTE, não da plataforma, mas convém avisar.', 'Lei Complementar 116/2003, lista anexa: item 1.03 ''Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres''; item 1.05 ''Licenciamento ou cessão de direito de uso de programas de computação''; item 1.07 ''Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados''. STF, ADI 1945 e ADI 5659, julgadas em 18/02/2021: incide ISS, e não ICMS, sobre o licenciamento de software, com modulação de efeitos aprovada em 24/02/2021.', 'Planalto — Lei Complementar 116/2003 (texto literal dos itens) + STF ADI 1945 e 5659', 'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm', '2026-10-06', 'Direito de arrependimento (CDC art. 49) em serviço digital de execução imediata. Emissão de nota por operação de valor pequeno. Se a OSC pode lançar como despesa de projeto.', 'A análise BÁSICA de prontidão é e continua gratuita. Esta regra cobra apenas a avançada, e os documentos desta rodada classificam a receita como aquisição, não núcleo.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- premium.document_preparation — carta YELLOW
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('premium.document_preparation', 'yellow', 'medium', 'Organização que propõe projeto', 'A plataforma', 'Documento montado e entregue', 'Receita de prestação de serviço de software, por operação', 'Contrato de adesão aos Termos de Uso', 'Termos aceitos; nota fiscal', 'Termos de Uso, Política de Reembolso, e aviso de que o documento é rascunho sujeito a revisão humana', 'Compra por operação', 'Mesmo ponto do art. 49 do CDC', 'ISS, mesmos itens.', 'Nota por operação, não implementada', 'RISCO PRÓPRIO desta regra: documento gerado com apoio de IA pode ser confundido com peça técnica de responsabilidade profissional. A plataforma já marca a saída como rascunho sujeito a revisão humana e exige aprovação a quatro olhos, mas a fronteira com atividade privativa de profissão regulamentada precisa de parecer.', 'Lei Complementar 116/2003, lista anexa: item 1.03 ''Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres''; item 1.05 ''Licenciamento ou cessão de direito de uso de programas de computação''; item 1.07 ''Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados''. STF, ADI 1945 e ADI 5659, julgadas em 18/02/2021: incide ISS, e não ICMS, sobre o licenciamento de software, com modulação de efeitos aprovada em 24/02/2021.', 'Planalto — Lei Complementar 116/2003 (texto literal dos itens) + STF ADI 1945 e 5659', 'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm', '2026-10-06', 'Fronteira com atividade privativa de profissão regulamentada (contabilidade, engenharia, advocacia) conforme o tipo de documento. Direito de arrependimento. Responsabilidade por erro no documento gerado.', 'O risco aqui não é tributário: é de responsabilidade técnica pelo conteúdo gerado.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;

-- data.territorial_intelligence — carta RED
WITH c AS (
  INSERT INTO monetization_legal_cards(rule_key, status, certainty, payer, beneficiary, billing_event, revenue_nature, contractual_relation, required_document, required_terms, cancellation_policy, refund_policy, tax_notes, invoice_notes, regulatory_notes, legal_basis, source_name, source_url, verified_on, open_questions, note)
  VALUES ('data.territorial_intelligence', 'red', 'medium', 'Órgão público, empresa ou fundação', 'A plataforma', 'Acesso contratado a painel, relatório ou API de inteligência agregada', 'Receita de prestação de serviço de informação', 'Contrato com cláusula específica de uso de dados', 'Contrato; nota fiscal; e registro da base legal do tratamento', 'Termos de uso de dados; e, para órgão público, os termos de contratação administrativa', 'Conforme contrato', 'Conforme contrato', 'Enquadramento depende de ser serviço de informação ou licenciamento de base. Não analisado.', 'Não implementada', 'O risco central é de PRIVACIDADE, não tributário. Dado anonimizado não é dado pessoal (LGPD art. 12), MAS deixa de valer essa regra se a anonimização puder ser revertida com esforços razoáveis — e agregado territorial com pouca contagem é exatamente onde a reidentificação acontece. Vender dado pessoal, ainda que indiretamente identificável, não está autorizado por nenhuma base legal aqui. Também é preciso definir quem é controlador do dado: a organização que o inseriu ou a plataforma.', 'Lei 13.709/2018 (LGPD), art. 5º, III: ''dado anonimizado'' é o dado relativo a titular que não possa ser identificado, considerando a utilização de meios técnicos razoáveis e disponíveis na ocasião de seu tratamento; art. 5º, XI define ''anonimização''. Art. 12: dado anonimizado não é dado pessoal, SALVO quando o processo de anonimização puder ser revertido com esforços razoáveis, considerando custo, tempo e tecnologias disponíveis.', 'Planalto — Lei 13.709/2018, arts. 5º, III e XI, e 12 (texto literal)', 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm', '2026-10-06', 'Limite mínimo de agregação para que a reversão não seja razoável. Quem é controlador. Base legal do tratamento para finalidade de produto. Necessidade de RIPD. Se os contratos com as organizações permitem uso agregado. TODAS exigem DPO e advogado.', 'VERMELHA. É o maior ticket potencial segundo os documentos e o maior risco de privacidade do produto. Nada deve ser construído aqui antes de RIPD e DPO nomeado.')
  RETURNING id, rule_key, status
)
UPDATE monetization_rules r SET legal_card_id = c.id,
       legal_status = CASE WHEN c.status = 'red' THEN 'refused' ELSE 'review_required' END
  FROM c WHERE r.key = c.rule_key;
