#!/usr/bin/env python3
"""Gera docs/analysis/economia_v0300/RELATORIO_EXECUTIVO_ECONOMIA_v0300.md a partir de resultados_120m.json (número nenhum à mão)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "analysis" / "economia_v0300"
R = json.loads((OUT / "resultados_120m.json").read_text(encoding="utf-8"))
SC = ("conservador", "base", "agressivo")
MARKS = (6, 12, 24, 48, 120)


def brl(c) -> str:
    if c is None:
        return "—"
    v = round(c) / 100
    s = f"{v:,.0f}".replace(",", "X").replace(".", ",").replace("X", ".")
    return f"R$ {s}"


def pct(x) -> str:
    return "—" if x is None else (f"{x * 100:.1f}%".replace(".", ",") if x <= 10 else f"{x * 100:.0f}% (>100%: inalcançável)")


L: list[str] = []
A = L.append
A("# Relatório executivo — Engenharia econômica, monetização híbrida, projeções e valuation (IMPACTO v0.30.0)")
A("")
A("> **Modo desta execução: ANÁLISE E PROPOSTA.** Nada do produto foi alterado: regra, catálogo, `config/plans.json`, banco e contratos")
A("> continuam exatamente como na v0.30.0. Todo número abaixo é SIMULAÇÃO sobre premissas declaradas (planilha `IMPACTO_MODELO_120M.xlsx`,")
A("> fórmulas abertas; motor em `scripts/analysis/economic_model_120m.py`; a planilha recalculada no LibreOffice reproduz o motor —")
A("> diferença máxima de arredondamento R$ 0,03). Natureza de cada premissa: **FATO** (repositório) · **HIPÓTESE DO PROPRIETÁRIO** (já")
A("> declarada no repositório) · **PREMISSA DE MERCADO** (não verificada, editável) · **DERIVADO** (cálculo). Receita real hoje: **R$ 0,00**.")
A("")
A("## 1. Diagnóstico econômico da base (FATOS do repositório, v0.30.0)")
A("")
A("| Item | Estado real | Onde está provado |")
A("|---|---|---|")
A("| Taxa de serviço | **350 bps (3,50 %)** sobre operação financiada, congelada no acordo; regra `contract.platform_service_fee` **INATIVA** (`review_required`, carta amarela) — nada é devido nem cobrado | `monetization_rules`, `config/economic_model.json`, `test_v0270_financial_model`, `test_v0150_upgrade` (11 regras, 0 ativas) |")
A("| Participação de autoria | **150 bps (1,50 %)**, do proponente elegível, **não é receita da plataforma** | ADR-337, `test_v0270_economy` |")
A("| Reconhecimento da receita transacional | só na **quitação** (entrega aceita + repasses confirmados por quem recebe); `allocation_payouts.state = 'awaiting_rule'` enquanto a regra estiver inativa | `MILESTONE_FUNDING_STATES_v0300.md`, `test_v0270_economy` |")
A("| GMV ≠ receita | o valor financiado vai do financiador ao projeto; a plataforma não custodia (nenhuma tabela de saldo/escrow: teste de estrutura) | ADR-284, `test_the_platform_has_no_table_that_holds_third_party_money` |")
A("| Assinaturas recorrentes | **não existem no código**: tabelas derrubadas na 0067; `GET /v1/plans` não publica preço recorrente; `config/plans.json` = pacotes de capacidades sem preço | ADR-341, `test_v0270_no_subscription` |")
A("| Regras recusadas no catálogo | `saas.institutional.funder`, `b2g.territorial_governance`, `data.territorial_intelligence`, `marketplace.take_rate`, `success_fee.funding` — **refused** com carta vermelha | `MONETIZATION_LEGAL_MATRIX.md` |")
A("| Regras em revisão | `contract.platform_service_fee`, `implementation.setup`, `enterprise.esg_portfolio`, `premium.readiness_analysis` (R$ 29 hipótese), `premium.document_preparation` (R$ 79 hipótese), `ai.credits_prepaid` (pacotes R$ 10 / 45 / 160, `hypothesis`; modo piloto) | catálogo; `ai_credit_packs`; ADR-349 |")
A("| Gateway de pagamento | nenhum; webhook responde 404 sem segredo; nenhuma cobrança real possível | `EXTERNAL_INTEGRATIONS.md`, `test_v0280_ai_usage_control` |")
A("| Custos | **não medidos**: sem folha, sem fatura de nuvem/provedor; `config/ai_economics.json` traz hipóteses (PIX 1 %, tributos 8,65 %, suporte R$ 0,30/usuário/mês, infra R$ 0,02/operação local) | `UNIT_ECONOMICS.md` (lado do custo `[PENDENTE]`) |")
A("| Invariantes | plano não altera match/elegibilidade/ranking; rebaixar não apaga dado; pagamento não compra posição | `config/plans.json` invariants, `test_v0150_invariants`, `test_v0270_no_subscription` |")
A("")
A("**Conflito encontrado (documento × decisão):** `UNIT_ECONOMICS.md` (v0.21.0) ainda descreve planos mensais (PRO R$ 299, BUSINESS R$ 799…). Está")
A("**superado** pela ADR-341 e pelo código (0067); **prevalece o código + ADR**. Recomendação: marcar o documento como SUPERADO (rodada de limpeza).")
A("")
A("**Conflito entre o pedido e a base:** a \"Camada 1 — SaaS institucional / receita previsível\" do pedido é, no repositório, a regra")
A("`saas.institutional.funder` **recusada** e a ADR-341 (\"não existe mais assinatura\"). O modelo abaixo avalia essa camada **como proposta**")
A("(desenho HÍBRIDO) sem confundi-la com o modelo vigente (desenho ATUAL). Ativar exige decisão do proprietário, ADR nova e parecer.")
A("")
A("## 2. Dois desenhos avaliados, sem mistura")
A("")
A("| Desenho | Fontes de receita | Base no repositório | O que muda |")
A("|---|---|---|---|")
A("| **ATUAL** | taxa 3,5 % sobre operações quitadas (quando a regra for ativada — premissa de mês de ativação) + serviços/inteligência avulsos (R$ 29/79, créditos) | catálogo vigente | nada — só precisa de parecer para ativar a taxa |")
A("| **HÍBRIDO** (proposta) | ATUAL + contratos institucionais **anuais** de software (governança, portfólio, auditoria, relatórios) com implantação | **contraria ADR-341**; regra recusada; faixas-hipótese do catálogo (R$ 2–10 mil/mês funder; R$ 3–15 mil ESG; R$ 3–50 mil gov) | ADR nova, catálogo, cartas, contrato-modelo, B2G só por licitação/dispensa |")
A("")
A("Diferença de natureza que o pedido exige preservar: contrato institucional **não é paywall** — o núcleo continua gratuito e nenhum")
A("contrato altera match, elegibilidade ou ranking (invariantes testados). O que se vende é operação de portfólio/governança para quem")
A("recebe valor econômico claro (financiador, governo, grande organização), nunca acesso para OSC.")
A("")
A("## 3. Matriz de monetização por fonte (FASE 2) — cada linha diz o que é fato e o que é hipótese")
A("")
A("| Fonte | Pagador | Problema resolvido | Evento de cobrança | Preço proposto (HIPÓTESE salvo nota) | Frequência | Custo de entrega | Margem de contribuição | Riscos | Impacto em OSC/beneficiários |")
A("|---|---|---|---|---|---|---|---|---|---|")
A("| A. Contrato institucional (HÍBRIDO) | financiador, fundação, grande organização; governo **só** por licitação/dispensa (Lei 14.133) | gerir portfólio com evidência, diligência, dossiês, relatórios ESG/ODS | assinatura do contrato anual (faturado na assinatura; reconhecido pro rata) | R$ 36 mil/ano (cons.) · R$ 72 mil/ano (base) · R$ 120 mil/ano (agr.) + implantação R$ 10–30 mil — **ancorado nas faixas-hipótese do catálogo recusado; sem evidência de mercado** | anual | suporte, implantação, infra variável (hipóteses) | alta se o produto já existe (é o caso: torres, dossiê, relatórios) | adoção não validada; ADR-341; B2G sem checkout | nenhum: OSC não paga; dados de OSC continuam dela |")
A("| B. Transacional (ATUAL) | financiador (pagador da cláusula) | operação rastreada até a quitação | **quitação** da operação | 3,50 % do valor financiado (**FATO**, catálogo); modo deducted/additional | por operação | registro; sem provedor | alta por operação; volume baixo nos tickets-hipótese | parecer (natureza da taxa; não é intermediação de pagamento — ADR-284/337); conflito de interesse mitigado por não-custódia e match sem pay-to-rank | em modo deducted o projeto recebe 95 %; em additional recebe 100 % |")
A("| C. Serviços profissionais (marketplace) | — | — | — | **não modelado como receita**: `marketplace.take_rate` recusada (vitrine sem pagamento interno) | — | — | — | instituição de pagamento (Lei 12.865) | — |")
A("| D. Inteligência (serviços avulsos) | OSC/pessoa/financiador que usa | prontidão, documento, créditos de IA, relatórios | entrega/execução bem-sucedida | R$ 29 / R$ 79 (hipóteses do catálogo); créditos R$ 0,10 (hipótese de teste); no modelo: R$ 1,50–8,00/OSC/mês e R$ 20–120/financiador/mês de adoção média (**PREMISSA DE MERCADO**) | por uso | provedor de IA (não contratado), horas | depende do provedor (`AI_COST_MODEL.md`: uma operação deficitária nomeada) | parecer (crédito pré-pago, CDC, NFS-e) | baixo preço; cota gratuita; patrocínio |")
A("")
A("## 4. Catálogo de preços proposto por perfil (FASE 3) — proposta, não decisão")
A("")
A("| Perfil | Núcleo gratuito | Contrato institucional (HÍBRIDO) | Módulos adicionais | Implantação/integração | Serviços avulsos | Transacional |")
A("|---|---|---|---|---|---|---|")
A("| Financiador / empresa / instituto | descoberta, candidaturas, diligência básica, acompanhamento | R$ 3–10 mil/mês (anual) — hipótese | ESG/ODS consolidado (R$ 3–15 mil/mês, hipótese do catálogo) | R$ 10–30 mil (hipótese) | relatórios/IA por uso | 3,5 % na quitação (fato; inativa) |")
A("| Governo / fundo | torre territorial, editais públicos | **só por licitação/dispensa**; faixa R$ 3–50 mil/mês (hipótese); **sem checkout** | — | por contrato | — | — (recurso público: regras próprias) |")
A("| Executora (OSC) | **tudo o que protege, corrige e presta contas** | nenhum (por desenho) | — | — | R$ 29 / R$ 79 / créditos (hipóteses); cota gratuita; patrocínio | não paga a taxa (quem paga é o financiador, modo additional) ou recebe 95 % (deducted) — definido no acordo |")
A("| Prestador | perfil, ofertas, entregas, reputação | nenhum | — | — | créditos de IA | sem comissão (recusada) |")
A("| Promotor de ideias | banco de ideias → projeto | nenhum | — | — | créditos de IA | — |")
A("")
A("**Evidência de mercado:** nenhuma faixa acima tem pesquisa de disposição a pagar; as únicas referências são as faixas-hipótese já escritas no")
A("catálogo (`hypothesis_note`) e os múltiplos externos citados em §6. Validar antes de desenvolver (roadmap §8).")
A("")
A("## 5. Projeção de 120 meses (FASE 4) — três cenários × dois desenhos")
A("")
A("Premissas comuns do repositório: 3 novos financiadores/mês (hipótese do proprietário); por cenário, ticket financiado, operações por")
A("financiador/ano, fração quitada e prazo de quitação (os mesmos de `config/economic_model.json`). Premissas de mercado (editáveis): churn,")
A("mês de ativação da taxa, inadimplência, prazo de recebimento, equipe, infra, marketing, CAC, contratos institucionais (só no HÍBRIDO).")
A("Custos de pessoal crescem com a carteira (1 FTE adicional a cada 15/20/25 clientes). Caixa inicial: zero (não informado).")
A("")
for design, title in (("atual", "Desenho ATUAL (modelo vigente)"), ("hibrido", "Desenho HÍBRIDO (proposta — contraria ADR-341)")):
    A(f"### 5.{1 if design == 'atual' else 2} {title}")
    A("")
    A("| Cenário | Marco | Financiadores | Contratos inst. | ARR software | Receita 12 m | — taxa | — software | — serviços | GMV originado 12 m | GMV quitado 12 m | EBITDA 12 m | Caixa | Mínimo de caixa até aqui |")
    A("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for sc in SC:
        for m in MARKS:
            d = R[sc][design]["milestones"][str(m)]
            A(f"| {sc} | M{m} | {d['funders']} | {d['inst_contracts']} | {brl(d['arr'])} | {brl(d['revenue_ttm'])} | {brl(d['fee_ttm'])} | {brl(d['software_ttm'])} | {brl(d['services_ttm'])} | {brl(d['gmv_originated_ttm'])} | {brl(d['gmv_settled_ttm'])} | {brl(d['ebitda_ttm'])} | {brl(d['cash'])} | {brl(d['min_cash_to_date'])} |")
    A("")
    A("| Cenário | Receita acumulada 120 m | Ponto de equilíbrio (mês, EBITDA > 0 sustentado) | Necessidade de capital (pior caixa) |")
    A("|---|---:|---:|---:|")
    for sc in SC:
        r = R[sc][design]
        A(f"| {sc} | {brl(r['milestones']['120']['revenue_cum'])} | {r['breakeven_month'] or 'não alcança em 120 m'} | {brl(r['capital_need_cents'])} |")
    A("")
A("**Leitura honesta:** no desenho ATUAL, com os tickets-hipótese do repositório, a taxa de 3,5 % sobre operações quitadas **não sustenta uma")
A("equipe** nos cenários conservador e base (o custo de pessoal cresce com a carteira mais rápido que a receita por financiador); só o")
A("cenário agressivo (ticket R$ 500 mil, 3 operações/ano) atinge equilíbrio. No HÍBRIDO, o contrato institucional é o que paga a operação;")
A("a taxa vira crescimento adicional. Isso é o que o pedido chamou de \"base de receita contratada para financiar a operação\" — e é exatamente")
A("o que a ADR-341 recusou como assinatura. **A decisão é do proprietário**, e o modelo mostra o preço de cada escolha.")
A("")
A("Modelagem separada que o pedido exige: **contratos assinados** (novos + renovações), **receita faturada** (anual na assinatura; taxa na")
A("quitação; serviços na entrega), **receita recebida** (prazo + inadimplência), **receita reconhecida** (software pro rata; taxa só na")
A("quitação e só após a ativação da regra), **GMV** (originado e quitado; nunca somado à receita), **participação de autoria** (coluna")
A("própria; nunca somada), **taxas e custos** (PIX sobre o recebido; tributos sobre o reconhecido — hipótese 8,65 %).")
A("")
A("## 6. Valuation e patrimônio do fundador (FASE 6) — faixas, com as premissas à vista")
A("")
A("Método: soma das partes — ARR de software × múltiplo SaaS + receita transacional líquida 12 m × múltiplo de marketplace + serviços 12 m ×")
A("múltiplo baixo — tudo × (1 − desconto por concentração, risco regulatório, iliquidez e dependência do fundador). EV/EBITDA só como")
A("cruzamento quando EBITDA > 0. **Nenhum múltiplo é aplicado a GMV.** Múltiplos por cenário: SaaS 2,5× / 4,0× / 6,0×; transacional 1,5× / 2,3× / 4,0×;")
A("serviços 1,0× / 1,5× / 2,0×; desconto 45 % / 35 % / 25 %. Diluição (premissa): 100 % → 85 % (M12) → 70 % (M24) → 55 % (M48) → 45 % (M120).")
A("")
A("Fontes externas (âncoras, não comparáveis diretos; nenhuma brasileira nem do terceiro setor): Software Equity Group, SaaS Index 2Q26 —")
A("mediana pública EV/Receita TTM **3,2×** (2Q25: 5,7×), M&A privado mediana **4,0×** e média 6,2× (lido via peony.ink em 09/10/2026);")
A("Aventis Advisors, SaaS Valuation Multiples 2015–2026 (abr/2026) — M&A privado mediana Q1 2026 3,1×, período 4,5×, negócios US$ 0–5 M ≈ 3,3×;")
A("SaaS Capital 2025 — múltiplo de ARR **modelado** 4,8–5,3×; Aventis, Marketplace Valuation Multiples 2025 (S&P Capital IQ, mar/2025) —")
A("público mediana EV/Receita **2,3×**, média histórica 5,6×, EV/EBITDA mediana 18×.")
A("")
for design, title in (("atual", "ATUAL"), ("hibrido", "HÍBRIDO")):
    A(f"### 6.{1 if design == 'atual' else 2} Desenho {title}")
    A("")
    A("| Cenário | Marco | EV software | EV transacional | EV serviços | Desconto | **EV (faixa do cenário)** | Cruzamento EV/EBITDA | Participação do fundador | Patrimônio teórico | Participação necessária para R$ 100 mi / 500 mi / 1 bi / US$ 1 bi |")
    A("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|")
    for sc in SC:
        for m in MARKS:
            v = R[sc][design]["valuation"][str(m)]
            need = v["share_needed"]
            needs = " / ".join(pct(need[k]) for k in ("R$ 100 milhões", "R$ 500 milhões", "R$ 1 bilhão", "US$ 1 bilhão"))
            A(f"| {sc} | M{m} | {brl(v['ev_saas'])} | {brl(v['ev_txn'])} | {brl(v['ev_services'])} | {v['discount_pct']:.0f}% | **{brl(v['ev'])}** | {brl(v['ev_ebitda_cross'])} | {v['founder_share'] * 100:.0f}% | {brl(v['founder_equity'])} | {needs} |")
    A("")
A("**O que esses números significam e o que não significam.** *Valuation* é o que a empresa poderia valer numa negociação sob estas premissas;")
A("*patrimônio teórico* é a participação do fundador vezes esse valor — **não é dinheiro disponível** (só vira caixa numa venda secundária ou")
A("saída, com desconto de iliquidez e tributos). Onde a participação necessária é > 100 %, a meta é **inalcançável** naquele marco e cenário.")
A("Marco em que cada meta de patrimônio do fundador cabe dentro da participação que a diluição-premissa deixa (DERIVADO):")
A("")
A("| Cenário / desenho | R$ 100 milhões | R$ 500 milhões | R$ 1 bilhão | US$ 1 bilhão |")
A("|---|---|---|---|---|")
for sc in SC:
    for design in ("atual", "hibrido"):
        cells = []
        for goal in ("R$ 100 milhões", "R$ 500 milhões", "R$ 1 bilhão", "US$ 1 bilhão"):
            hit = next((m for m in MARKS if R[sc][design]["valuation"][str(m)]["share_needed"][goal] <= R[sc][design]["valuation"][str(m)]["founder_share"]), None)
            cells.append(f"M{hit}" if hit else "não alcança em 120 m")
        A(f"| {sc} / {design} | " + " | ".join(cells) + " |")
A("")
ag = R["agressivo"]["hibrido"]["valuation"]["120"]
ev_for_100m = 100_000_000_00 / ag["founder_share"]
A(f"Nenhuma meta cabe em nenhum cenário do repositório. Com {ag['founder_share'] * 100:.0f}% de participação em M120, R$ 100 milhões de patrimônio")
A(f"teórico exigiriam valuation de {brl(ev_for_100m)}; o melhor cenário modelado (agressivo híbrido) chega a {brl(ag['ev'])} em M120 — ou seja,")
A(f"faltam {ev_for_100m / ag['ev']:.1f}× em valor, e R$ 1 bilhão exigiria 10× isso. A resposta à pergunta \"qual ritmo é necessário\" é: tickets,")
A("volumes e contratos acima do cenário agressivo (ou diluição muito menor), para os quais **não há evidência hoje**. A planilha permite testar")
A("que combinação de contratos, operações, preços e custos chegaria lá — mas um número que a planilha calcula não é uma previsão.")
A("")
A("## 7. Sensibilidade e testes de estresse (FASE 7) — cenário Base, desenho HÍBRIDO")
A("")
A("| Choque | Receita acumulada 120 m | Necessidade de capital | Ponto de equilíbrio | Caixa em M120 | EV em M48 |")
A("|---|---:|---:|---:|---:|---:|")
base = R["base"]["hibrido"]
A(f"| (referência: Base híbrido) | {brl(base['milestones']['120']['revenue_cum'])} | {brl(base['capital_need_cents'])} | {base['breakeven_month']} | {brl(base['milestones']['120']['cash'])} | {brl(base['valuation']['48']['ev'])} |")
for k, v in R["sensibilidade"].items():
    A(f"| {k} | {v['delta_revenue_120_pct']:+.1f}% | {brl(v['capital_need_cents'])} | {v['breakeven_month'] or 'não alcança'} | {brl(v['cash_m120_cents'])} | {brl(v['ev_m48_cents'])} |")
A("")
A("**Variáveis que mais afetam caixa, sobrevivência e valuation:** (1) existência e ritmo dos **contratos institucionais** — sem eles o desenho")
A("volta ao ATUAL e não há equilíbrio nos cenários conservador/base; (2) **ticket financiado** e **operações por financiador** (a taxa é")
A("percentual de um volume que a plataforma não controla); (3) **ativação da taxa** (parecer) — se nunca ativar, resta software + serviços;")
A("(4) **custo de pessoal por cliente**; (5) churn/concentração. Inadimplência e prazo de quitação pesam menos que os cinco acima.")
A("")
A("## 8. Riscos, conformidade e o que precisa de parecer (FASE 8)")
A("")
A("| Tema | Risco | Estado no repositório | Para parecer |")
A("|---|---|---|---|")
A("| Cobrança por intermediação / taxa de êxito | enquadramento como instituição de pagamento (Lei 12.865/2013, art. 6º) e conflito de interesse | `success_fee.funding` e `marketplace.take_rate` **recusadas**; não custodial (ADR-284) | não reabrir sem advogado de meios de pagamento |")
A("| Natureza da taxa de serviço (3,5 %) | serviço de software (ISS/NFS-e) × intermediação; base de cálculo; modo deducted (projeto recebe menos) | carta amarela; regra inativa; `fee_mode` no acordo | parecer jurídico + contábil antes da carta verde |")
A("| Contratos com entes públicos | Lei 14.133/2021: licitação / dispensa / inexigibilidade não analisadas | `b2g.territorial_governance` recusada; **sem checkout para governo** | advogado de contratações públicas; modelo de edital/termo |")
A("| Contrato institucional anual (HÍBRIDO) | reintroduz receita recorrente que a ADR-341 retirou; tributação (ISS, Simples/Presumido), reajuste, cancelamento, CDC não se aplica a B2B mas aplica-se a pessoa física | não existe | decisão do proprietário + ADR + parecer contábil |")
A("| Créditos de IA pré-pagos | reconhecimento (obrigação até consumo), validade/devolução (CDC), NFS-e | piloto; carta amarela | parecer antes de venda real |")
A("| Recursos de terceiros | nunca tratados como caixa próprio; nenhuma tabela de saldo; conciliação manual | provado por teste | manter; qualquer parceiro de pagamento exige revisão |")
A("| Dados territoriais como produto | LGPD (reidentificação em agregados pequenos); DPO inexistente | `data.territorial_intelligence` recusada | RIPD + DPO antes de qualquer produto de dado |")
A("| Tributos no modelo | 8,65 % é **hipótese** (não é regime definido) | `config/ai_economics.json` | contador define regime e alíquotas |")
A("")
A("## 9. Roadmap de execução (FASE 9) — validação comercial antes de funcionalidade cara")
A("")
A("| Horizonte | Iniciativa | Valor esperado | Custo | Responsável | Dependências | Risco | Métrica de sucesso | Critério de interrupção |")
A("|---|---|---|---|---|---|---|---|---|")
A("| 0–90 dias | Parecer jurídico/contábil da taxa de serviço (carta verde) e da matriz de elegibilidade de cobrança | destravar a única receita transacional já construída | honorários (não estimados) | proprietário | advogado(a), contador(a) | parecer negativo | carta verde registrada; regra ativável | parecer contrário à natureza de serviço de software |")
A("| 0–90 dias | **Validação comercial** do contrato institucional: 10 conversas com financiadores/fundações, 3 cartas de intenção com preço | evidência de disposição a pagar (hoje zero) | tempo do fundador | proprietário | dossiê e torres já existem (v0.26–0.30) | ninguém paga | ≥ 3 LOIs com valor ≥ R$ 3 mil/mês | 0 LOIs em 90 dias → não reabrir ADR-341 |")
A("| 0–90 dias | Medir custos reais (folha planejada, nuvem, suporte) e substituir as premissas de mercado da planilha | modelo deixa de ser hipótese sobre hipótese | baixo | proprietário | faturas | — | `UNIT_ECONOMICS.md` sem `[PENDENTE]` de custo | — |")
A("| 3–6 meses | Se houver LOIs: ADR nova + catálogo (regra `enterprise.esg_portfolio`/implantação ativáveis por contrato avulso) + contrato-modelo | primeiros contratos | desenvolvimento pequeno (proposta/aceite já existem: `offer_acceptances`) | proprietário + dev | ADR, parecer | reintroduzir paywall por descuido | 3 contratos assinados e faturados | invariantes quebrados (teste) |")
A("| 3–6 meses | Piloto da taxa de serviço em 3 operações reais com carta verde | primeira receita transacional reconhecida | — | proprietário + 1 financiador âncora | parecer; `PLATFORM_PIX_KEY` | quitação não acontece | 3 operações quitadas e taxa paga | nenhuma quitação em 6 meses |")
A("| 6–12 meses | B2G por procedimento (dispensa/inexigibilidade) com 1 órgão | contrato público | jurídico | proprietário | Lei 14.133 | prazo público | 1 contrato | — |")
A("| 12–24 meses | Reavaliar múltiplos e cenários com 12 meses de dados reais; decidir capital (ou não) | plano de capital baseado em fato | — | proprietário | histórico | — | modelo recalibrado | — |")
A("")
A("## 10. Decisões que dependem do proprietário")
A("")
A("1. **Reabrir ou não a ADR-341** para contratos institucionais anuais (desenho HÍBRIDO). O modelo mostra que, nos cenários conservador e base, sem eles não há equilíbrio.")
A("2. **Ativar a taxa de serviço** (carta verde) — depende de parecer; definir modo padrão (`deducted`/`additional`) e quem paga.")
A("3. **Preços**: aceitar as faixas-hipótese (R$ 36/72/120 mil por ano; implantação R$ 10–30 mil; R$ 29/79; créditos) como preços de **teste** com validação comercial, ou pesquisar antes.")
A("4. **B2G**: investir em procedimento de contratação pública ou adiar.")
A("5. **Capital**: aceitar necessidade de capital estimada (hipótese) ou crescer com caixa (menos FTE) — a planilha permite testar.")
A("6. **Regime tributário** e estrutura societária (diluição-premissa) — contador(a).")
A("7. **UNIT_ECONOMICS.md** superado: marcar e substituir pelo modelo de 120 meses quando os custos forem medidos.")
A("")
A("## 11. Lacunas e como medi-las")
A("")
A("| Lacuna | Como medir | Prazo sugerido |")
A("|---|---|---|")
A("| Disposição a pagar por contrato institucional | 10 entrevistas + 3 LOIs com preço | 90 dias |")
A("| Ticket e frequência reais de operações | 3 operações piloto quitadas | 6 meses |")
A("| Custo de pessoal, nuvem, suporte | folha planejada + 3 faturas | 30 dias |")
A("| Churn e concentração | 12 meses de carteira | 12 meses |")
A("| Alíquotas | parecer contábil | 30 dias |")
A("| Múltiplos aplicáveis ao Brasil/terceiro setor | comparáveis privados (não encontrados nesta rodada) | contínuo |")
A("")
A("## 12. Entregáveis desta análise")
A("")
A("`IMPACTO_MODELO_120M.xlsx` (premissas editáveis, 6 abas mensais com fórmulas abertas, marcos, fontes; recalculada e conferida), `resultados_120m.json`,")
A("gráficos `g1`–`g9` (PNG), este relatório (MD e DOCX), `scripts/analysis/economic_model_120m.py` (motor) e `make_economic_report.py` (este texto).")
A("**Nenhuma alteração no produto.** A FASE 10 (implementação) só começa com a aprovação explícita das decisões do §10.")
(OUT / "RELATORIO_EXECUTIVO_ECONOMIA_v0300.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print("ok", len(L), "linhas")
sys.exit(0)
